[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.86.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.86.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
